# Channel Grabber
# Author: Larry Donahue
# This program aims to scrape channel data generated by fscan in order to provide data for the Linefinder Interface located at https://github.com/donahuel/linefinder-interface to use, and then write said channel data to a channels.txt file.
# This program is intended for use on the LIGO clusters, and lives there.

import os
import subprocess

def scrape():
        #Define root directory to scrape channel names from:
        rootdir = "data"

        #List of channels:
        channels = []

        #For loop that runs through directory:
        for subdir, dirs, files in os.walk(rootdir): #Walk through (almost) every directory/subdirectory within the root directory
                print("Current directory: " + subdir)
                if len(subdir.split('/')) == 5: #This is how we know we've hit a channel directory.
                        if subdir.split('/')[4] not in channels:
                                channels.append(subdir.split('/')[4]) #This adds the channel to the list, if it already isn't in the list.

        return channels

def write(channels):
        chanFile = open("channels.txt", "w")
        for channel in channels:
                chanFile.write(channel + "\n")
        chanFile.close()

print("Channel Grabber opened. Starting the gathering...")
channels = scrape()
print(str(len(channels)) + " unique channels found. Writing to file channels.txt...")
write(channels)
print("File written.")
